### ISSUE TITLE
problem create ifcSite , ifcBuilding , ifcBuildingStorey by default without need it 

### ISSUE THREAD

**Issue by mohamedelbadry** [BIM-Tools/SketchUp-IFC-Manager#1]
hello .. 
why when i make export my ifc project that contain (ifcsit , ifcBuilding  and ifcBuildingstories)  from SU
then import this into any ifc viewer like solibry i found ifcSite  , ifcBuilding  and ifcBuildingstorry addition to my ifcsit , ifcBuilding  and ifcBuildingstories .
i try to found a code that responsible for that but i could not   :D 

note : this link contains pic that shows hierarchical for my project
[https://drive.google.com/open?id=1bHvlB1ZkGZvXHdNSRjgEe14tYLp07kig](url)

**Comment by SvSchaijk** [comment]
Hi, I think that you have modelled some objects outside your defined building. 
The plugin makes a default building when objects do not contain any building or site.
You can check that in your outliner. 

Best regards,

Stijn

**Comment by mohamedelbadry** [comment]
thanks for your response .. it's works now but i have another thing, each element in my project exported with its global id instead of its name. i think you must using  entity.name  instead of entity.definition.name to get name of its entity ,

**Comment by mohamedelbadry** [comment]
i solved it now

**Comment by janbrouwer** [comment]
Thanks for pointing out these issues! Sorry it took a while to answer...
I don't underdstand what goes wrong here, the screenshot you posted looks very strange to me.
I use the definition name on purpose because that's also the SketchUp component's name. The instance name is not always present, and it could be different for each placement.
I have been testing this and I never get a globalid instead of a name. What version of SketchUp are you using, mac version maybe?

**Comment by mohamedelbadry** [comment]
hello sir..
when you start your ifc project in sketchtup there is no problem ..but if importing any ifc file into sketchup you will faces this problem ..
could you test importing ifc file and check for all attribute of entities

**Comment by janbrouwer** [comment]
Ah! Thanks, I'll check it out!
