### ISSUE TITLE
import crash

### ISSUE THREAD

**Issue by Hodepinemannen** [BIM-Tools/SketchUp-IFC-Manager#19]
hi
Tried importing ifc with v 3.4.1. That crashed. Some files, like the one I used, crash with the native importer as well. ( I assume the import button uses the native sketchup  ifc import ?). This only happens on the Mac though, the issue is reported to Trimble.

**Comment by janbrouwer** [comment]
Yes, it just calls the native importer and does some modifications afterwards, if the internal importer crashes then I'm afraid there's nothing I can do.
Does the rest of the extension work well on Mac? I don't get much chance to test that.

**Comment by Hodepinemannen** [comment]
Hi

Just started using that version today. I will let you know.

mvh
Odd Håkon Byberg

**Comment by Hodepinemannen** [comment]
hi. I find that in preferences one can tick the Netherland standard and the DIN (German) standard at the same time. Does that make sense? (screenshot attached)

It would be nice for the rest of the world  :-)   if one could choose an ISO (international) standard from building smart, as that is the basis for ifc definitions (iso-standards and the ifc 2x3 and upwards series). Its probably just a matter of adding the lists of building part definitions, they are probably much the same, but in English.
<img width="358" alt="Skjermbilde 2021-01-08 kl  17 49 27" src="https://user-images.githubusercontent.com/77156933/104045678-3396a680-51df-11eb-8e3f-98194704191d.png">

**Comment by janbrouwer** [comment]
Adding the dutch standard to sketchup ifc was the original purpose of the extension 😄. It's the most important thing in ifc models (other then the ifc entity type) here. The German classification was later submitted by malte palmen. A lot of the work for this version went into "internationalizing" the extension. You can now turn classifications on and off. And although it won't be used very much you can indeed classify objects for german and dutch systems in the same model without issue in the resulting IFC. Nicely fits the sketchup classifier tool. But the main reason for the changes (switching classifications on and off) is so that other people can now easily add more classifications! So if you have your local (or iso) system as a .skc I would be happy to help adding it to the extension. https://help.sketchup.com/en/sketchup/classifying-objects look for "Creating an SKC file"

**Comment by Hodepinemannen** [comment]
I´m more of a user kind_of_person, but I've asked someone more capable do chip in. You should sell the thing to Trimble, as their ifc-stuff works so bad. I hear rumors they are working on it, so that sounds like double work..:-) 

mvh
Odd Håkon Byberg

siv ark Odd Håkon Byberg AS
Nordregt. 8
7011 Trondheim
tlf 96 22 77 66
odd.byberg@me.com <mailto:odd.byberg@me.com>
