### ISSUE TITLE
Properties not exporting

### ISSUE THREAD

**Issue by ricottatiago** [BIM-Tools/SketchUp-IFC-Manager#33]
While using the latest version (4.1.1) the properties of the components does not export :(

**Comment by janbrouwer** [comment]
Hi @ricottatiago,
thanks for the feedback, IfcProperties seem to work pretty well here.
Can you explain a little bit more? Maybe add an example?

Two things that I'm aware of:

1. You must add properties to the exported classification system in Sketchup, for example when you add properties to IFC2x3 they will only be exported when this version is active on export, when selecting only on export IFC4 you will get empty unclassified objects. I'm thinking about adding some kind of conversion tool to move data between IFC versions inside Sketchup
2. ElementQuantities are still incorrectly exported as Propertysets

**Comment by ricottatiago** [comment]
Hi @janbrouwer 
Sorry, I should have given more info about the problem, here is a very simple example from SketchUp and the IFC file exported:
[Sketch-IFC.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/8084761/Sketch-IFC.zip)
I checked the IFC file and there is no Propertysets that were exported.

**Comment by janbrouwer** [comment]
What I did change is that empty properties are no longer exported, is that what you mean?
I removed them all because I agree with https://github.com/BIM-Tools/SketchUp-IFC-Manager/issues/23#issuecomment-844944451 that empty properties never make sense.

The only other thing that I can find in your model is a dynamic component attribute Custom -> Area, but that is not exported because the property is also hidden in sketchup, and only properties that are visible in the dynamic components options dialog are exported and dynamic component attributes according to https://github.com/BIM-Tools/SketchUp-IFC-Manager/wiki/Parametric-Property-Sets

If that's not what you meant than I'm unable to find the properties that are in Sketchup and missing from IFC.

Oh and one last option could be that you expect the Pset_WallCommon in the model, but that is only added when the IfcWall type is set from the IFC Manager properties window (not when using the sketchup native classification tool).

**Comment by ricottatiago** [comment]
That is exactly what happened, I was used to have all the information exported from the component, but it is a good idea to export only what is visible, it makes perfect sense and the problem was with me... I just made the attribute visible and worked perfectly.
Thinking in the UX, maybe the user could choose to export only what is visible from Dynamic Components, sometimes it is just faster to do that.
Good work on the IFC types, that's awesome.

**Comment by janbrouwer** [comment]
> Thinking in the UX, maybe the user could choose to export only what is visible from Dynamic Components, sometimes it is just faster to do that even if there is the burden of exporting empty stuff.

I'm not sure if that's worth the complexity of another option in the settings window, it's getting quite complicated already. I almost always have lots of 'helper' attributes in dynamic components that wouldn't make much sense as an IfcProperty. I will think on it ;-)

> Good work on the IFC types, that's awesome.

Thanks! :-D
